/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class AtualizarDados extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarDados
     */
    public AtualizarDados() {
        initComponents();
        getRootPane().setDefaultButton(jButtonAtualizar);
        this.setSize(850, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("#### - ####");
            jTextFieldBusca =  new javax.swing.JFormattedTextField(telefone);
        }
        catch(Exception e){
        }
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCpf = new javax.swing.JTextField();
        jTextFieldTelefone1 = new javax.swing.JTextField();
        jTextFieldTelefone2 = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldPlano = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Dados");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel1.setText("Telefone do Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 132, 176, 37);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel2.setText("Novo Cpf");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 231, 131, 37);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel3.setText("Novo Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 182, 131, 37);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel4.setText("Novo Telefone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 278, 131, 37);

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel5.setText("Novo Telefone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 327, 131, 37);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel6.setText("Novo Endereço");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 376, 131, 37);

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel7.setText("Novo Plano");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 425, 131, 37);

        jTextFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaActionPerformed(evt);
            }
        });
        jTextFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldBusca);
        jTextFieldBusca.setBounds(200, 132, 329, 37);

        jTextFieldNome.setEnabled(false);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(200, 184, 326, 34);

        jTextFieldCpf.setEnabled(false);
        getContentPane().add(jTextFieldCpf);
        jTextFieldCpf.setBounds(200, 231, 326, 34);

        jTextFieldTelefone1.setEnabled(false);
        getContentPane().add(jTextFieldTelefone1);
        jTextFieldTelefone1.setBounds(200, 278, 326, 42);

        jTextFieldTelefone2.setEnabled(false);
        getContentPane().add(jTextFieldTelefone2);
        jTextFieldTelefone2.setBounds(200, 327, 326, 34);

        jTextFieldEndereco.setEnabled(false);
        getContentPane().add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(200, 374, 326, 34);

        jTextFieldPlano.setEnabled(false);
        getContentPane().add(jTextFieldPlano);
        jTextFieldPlano.setBounds(200, 421, 326, 32);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7824_64x64.png"))); // NOI18N
        jLabel8.setText("Editar Dados");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(27, 13, 306, 101);

        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7881_64x64.png"))); // NOI18N
        jButtonAtualizar.setEnabled(false);
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar);
        jButtonAtualizar.setBounds(707, 633, 97, 73);

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7890_64x64_1.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(12, 633, 97, 73);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo_1_1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(560, 10, 262, 110);

        jButtonPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconelupa.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(540, 120, 88, 60);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit-clear_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(574, 633, 97, 73);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-2, -4, 840, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        if ((jTextFieldNome.getText().isEmpty()) && (jTextFieldCpf.getText().equals("   .   .   -  ")) && (jTextFieldTelefone1.getText().equals("     -     ")) && (jTextFieldEndereco.getText().isEmpty())) {

            JOptionPane.showMessageDialog(rootPane, "Os campos não podem retornar vazios");

        } else 
            if ((jTextFieldNome.getText().isEmpty())) {

                JOptionPane.showMessageDialog(rootPane, "O campo NOME não pode retornar vazio");
            } else 
                if ((jTextFieldEndereco.getText().isEmpty())) {

                    JOptionPane.showMessageDialog(rootPane, "O campo ENDEREÇO não pode retornar vazio");

                } else 
                    if ((jTextFieldTelefone1.getText().equals("     -     "))) {

                        JOptionPane.showMessageDialog(rootPane, "O campo TELEFONE 1 não pode retornar vazio");
                    } else {
                        if ((jTextFieldCpf.getText().equals("   .   .   -  "))) {

                            JOptionPane.showMessageDialog(rootPane, "O campo CPF não pode retornar vazio");

                        
                    
                
            }else {
                            try {
                                //Registra JDBC driver
                                Class.forName("com.mysql.jdbc.Driver");

                                //Abrindo a conexão
                                Connection conn = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/sica?zeroDateTimeBehavior=convertToNull", "sica", "1122448816");

                                //Executa a query de atualização
                                java.sql.Statement st = conn.createStatement();
                                st.executeUpdate("UPDATE Usuarios SET nome='"
                                        + this.jTextFieldNome.getText() + "',plano='"
                                        + this.jTextFieldPlano.getText() + "',cpf='"
                                        + this.jTextFieldCpf.getText() + "',telefone1='"
                                        + this.jTextFieldTelefone1.getText() + "',telefone2='"
                                        + this.jTextFieldTelefone2.getText() + "',endereço='"
                                        + this.jTextFieldEndereco.getText()
                                        + "' WHERE telefone1='" + this.jTextFieldBusca.getText() + "'");
                                JOptionPane.showMessageDialog(rootPane, "Aluno atualizado");
                            } catch (SQLException | ClassNotFoundException e) {
                                JOptionPane.showMessageDialog(rootPane, e);
                            }
                        }
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/sica?zeroDateTimeBehavior=convertToNull", "sica", "1122448816");

            java.sql.Statement st = conn.createStatement();
            st.executeQuery("Select * FROM Usuarios WHERE telefone1='" + this.jTextFieldBusca.getText() + "'");
            ResultSet rs = st.getResultSet();

            if (jTextFieldBusca.getText().equals("     -     ")) {
                JOptionPane.showMessageDialog(rootPane, "Campo de Busca não pode retornar vazio!");
            } else {
                while (rs.next()) {

                    jTextFieldNome.setText(rs.getString("nome"));
                    jTextFieldCpf.setText(rs.getString("cpf"));
                    jTextFieldPlano.setText(rs.getString("plano"));
                    jTextFieldTelefone1.setText(rs.getString("telefone1"));
                    jTextFieldTelefone2.setText(rs.getString("telefone2"));
                    jTextFieldEndereco.setText(rs.getString("endereço"));
                }
                if (jTextFieldNome.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Aluno não existe! O número está incorreto !");
                } else {

                    jButtonAtualizar.setEnabled(true);
                    jTextFieldNome.setEnabled(true);
                    jTextFieldCpf.setEnabled(true);
                    jTextFieldPlano.setEnabled(true);
                    jTextFieldTelefone1.setEnabled(true);
                    jTextFieldTelefone2.setEnabled(true);
                    jTextFieldEndereco.setEnabled(true);
                }
            }

        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }


    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextFieldBusca.setText("");
        jTextFieldNome.setText("");
        jTextFieldCpf.setText("");
        jTextFieldPlano.setText("");
        jTextFieldTelefone1.setText("");
        jTextFieldTelefone2.setText("");
        jTextFieldEndereco.setText("");

        jButtonAtualizar.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jTextFieldCpf.setEnabled(false);
        jTextFieldPlano.setEnabled(false);
        jTextFieldTelefone1.setEnabled(false);
        jTextFieldTelefone2.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jButtonPesquisar.doClick();

        }

    }//GEN-LAST:event_jTextFieldBuscaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPlano;
    private javax.swing.JTextField jTextFieldTelefone1;
    private javax.swing.JTextField jTextFieldTelefone2;
    // End of variables declaration//GEN-END:variables
}
