/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.Usuarios;

import controle.CPF;
import dao.UsuarioDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class Cadastro extends javax.swing.JFrame {

   

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        getRootPane().setDefaultButton(jButtonCadastrar);
        this.setSize(845, 630);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCpf = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##");
            jTextFieldCpf =  new javax.swing.JFormattedTextField(cpf);
        }
        catch(Exception e){
        }
        jTextFieldPlano = new javax.swing.JTextField();

        jTextFieldTelefone1 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone1 = new javax.swing.text.MaskFormatter("#### - ####");
            jTextFieldTelefone1 =  new javax.swing.JFormattedTextField(telefone1);
        }
        catch(Exception e){
        }
        jTextFieldTelefone2 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone2 = new javax.swing.text.MaskFormatter("#### - ####");
            jTextFieldTelefone2 =  new javax.swing.JFormattedTextField(telefone2);
        }
        catch(Exception e){
        }
        jTextFieldEndereco = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 141, 78, 33);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel3.setText("CPF");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 388, 78, 33);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel4.setText("Plano");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 245, 78, 33);

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel5.setText("Telefone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 296, 78, 33);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel6.setText("Telefone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 342, 78, 33);

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel7.setText("Endereço");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 194, 78, 33);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(95, 142, 688, 33);

        jTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfActionPerformed(evt);
            }
        });
        jTextFieldCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCpfKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldCpf);
        jTextFieldCpf.setBounds(97, 389, 690, 32);
        getContentPane().add(jTextFieldPlano);
        jTextFieldPlano.setBounds(95, 246, 690, 32);

        jTextFieldTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefone1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefone1);
        jTextFieldTelefone1.setBounds(96, 297, 690, 32);
        getContentPane().add(jTextFieldTelefone2);
        jTextFieldTelefone2.setBounds(96, 343, 690, 32);
        getContentPane().add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(95, 195, 690, 32);

        jButtonCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7881_64x64.png"))); // NOI18N
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(670, 510, 137, 70);

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7890_64x64_1.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(30, 510, 137, 70);

        jButtonLimpar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit-clear_1.png"))); // NOI18N
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(510, 510, 140, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo_1_1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 282, 96);

        jLabel9.setText("*");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(790, 150, 20, 16);

        jLabel10.setText("*");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(790, 200, 8, 16);

        jLabel11.setText("*");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(788, 305, 8, 16);

        jLabel12.setText("*");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(788, 351, 8, 16);

        jLabel13.setText("*");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(788, 397, 8, 16);

        jLabel14.setText("* Campos Obrigatórios");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(650, 440, 132, 16);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7818_64x64.png"))); // NOI18N
        jLabel15.setText("Cadastro de Cliente");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(530, 10, 270, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(845, 623));
        jLabel1.setMinimumSize(new java.awt.Dimension(845, 623));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldNome.setText("");
        jTextFieldCpf.setText("");
        jTextFieldPlano.setText("");
        jTextFieldTelefone1.setText("");
        jTextFieldTelefone2.setText("");
        jTextFieldEndereco.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed

        String cpf = null;

        Usuarios usuarios = new Usuarios();
        usuarios.setNome(jTextFieldNome.getText());
        usuarios.setCpf(jTextFieldCpf.getText());
        usuarios.setPlano(jTextFieldPlano.getText());
        usuarios.setTelefone1(jTextFieldTelefone1.getText());
        usuarios.setTelefone2(jTextFieldTelefone2.getText());
        usuarios.setEndereço(jTextFieldEndereco.getText());

        cpf = jTextFieldCpf.toString();
        if ((jTextFieldNome.getText().isEmpty()) && (jTextFieldCpf.getText().equals("   .   .   -  ")) && (jTextFieldTelefone1.getText().equals("     -     ")) && (jTextFieldEndereco.getText().isEmpty())) {

            JOptionPane.showMessageDialog(rootPane, "Os campos não podem retornar vazios");

        } else 
            if ((jTextFieldNome.getText().isEmpty())) {

                JOptionPane.showMessageDialog(rootPane, "O campo NOME não pode retornar vazio");
            } else 
                if ((jTextFieldEndereco.getText().isEmpty())) {

                    JOptionPane.showMessageDialog(rootPane, "O campo ENDEREÇO não pode retornar vazio");

                } else 
                    if ((jTextFieldTelefone1.getText().equals("     -     "))) {

                        JOptionPane.showMessageDialog(rootPane, "O campo TELEFONE 1 não pode retornar vazio");
                    } else {
                        if ((jTextFieldCpf.getText().equals("   .   .   -  "))) {

                            JOptionPane.showMessageDialog(rootPane, "O campo CPF não pode retornar vazio");


            } else {
                if (!(new CPF(jTextFieldCpf.getText())).isValidCPF()) {
                    JOptionPane.showMessageDialog(rootPane, "CPF inválido");

                } else {

                    UsuarioDAO dao = new UsuarioDAO();

                    try {
                        dao.adicionarClientes(usuarios);
                    } catch (SQLException ex) {
                        Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(null, "Usuário " + jTextFieldNome.getText() + " inserido com sucesso! ");

                    jTextFieldNome.setText("");
                    jTextFieldCpf.setText("");
                    jTextFieldPlano.setText("");
                    jTextFieldTelefone1.setText("");
                    jTextFieldTelefone2.setText("");
                    jTextFieldEndereco.setText("");
                }

            }
        }


    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed


    }//GEN-LAST:event_jTextFieldCpfActionPerformed

    private void jTextFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyTyped
        String caracteres = "0987654321";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldNomeKeyTyped

    private void jTextFieldCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfKeyPressed

    private void jTextFieldTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefone1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPlano;
    private javax.swing.JTextField jTextFieldTelefone1;
    private javax.swing.JTextField jTextFieldTelefone2;
    // End of variables declaration//GEN-END:variables
}
