/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Victor
 */
public class HomeSecretario extends javax.swing.JFrame {
     
  
   
    /**
     * Creates new form Home
     */
    public HomeSecretario() {
        initComponents();
        this.setSize(768, 650);
        
        jButtonExcluir.setEnabled(false);
        jButtonCadastroUsuario.setEnabled(false);
        
        
   
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadatro = new javax.swing.JButton();
        jButtonLocalizar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonCadastroUsuario = new javax.swing.JButton();
        jButtonTrocaUsu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" SICA Beta 2015");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("SICA"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonCadatro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadatro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7818_64x64.png"))); // NOI18N
        jButtonCadatro.setToolTipText("Cadastro");
        jButtonCadatro.setBorder(null);
        jButtonCadatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadatroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadatro);
        jButtonCadatro.setBounds(90, 90, 100, 110);

        jButtonLocalizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7833_64x64.png"))); // NOI18N
        jButtonLocalizar.setToolTipText("Localizar");
        jButtonLocalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLocalizar);
        jButtonLocalizar.setBounds(270, 90, 100, 110);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(10, 550, 127, 40);

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7822_64x64.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(460, 90, 100, 110);

        jButtonAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7824_64x64.png"))); // NOI18N
        jButtonAtualizar.setToolTipText("Editar dados");
        jButtonAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar);
        jButtonAtualizar.setBounds(270, 310, 100, 110);

        jButtonCadastroUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7764_64x64.png"))); // NOI18N
        jButtonCadastroUsuario.setToolTipText("Cadastro de Usuarios");
        jButtonCadastroUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroUsuario);
        jButtonCadastroUsuario.setBounds(80, 310, 100, 110);

        jButtonTrocaUsu.setText("Trocar Usuario");
        jButtonTrocaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrocaUsuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTrocaUsu);
        jButtonTrocaUsu.setBounds(10, 510, 129, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo_1_1.png"))); // NOI18N
        jLabel1.setText("Logo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 260, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1, -4, 770, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadatroActionPerformed
        gui.Login login = new Login();
        
        Cadastro ja = new Cadastro();
        ja.setVisible(true);

    }//GEN-LAST:event_jButtonCadatroActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed

        Busca jb = new Busca();
        jb.setVisible(true);
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        Exclusao ex = new Exclusao();
        ex.setVisible(true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        AtualizarDados at = new AtualizarDados();
        at.setVisible(true);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioActionPerformed
        CadastroUsuario cu = new CadastroUsuario();
        cu.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroUsuarioActionPerformed

    private void jButtonTrocaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrocaUsuActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        Login lo = new Login();
        lo.setVisible(true);

    }//GEN-LAST:event_jButtonTrocaUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeSecretario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeSecretario().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastroUsuario;
    private javax.swing.JButton jButtonCadatro;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTrocaUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
